### ISSUE TITLE
Artist and Album line breaks, too

### ISSUE THREAD

**Issue by Shadester** [hankhank10/music-screen-api#4]
Looks like a lot of times album names and artists can be too long, too. It would be great to have reflow on that too.

By the way, this is awesome! Love it on my inky WHAT.

**Comment by hankhank10** [comment]
It should line break automatically. Can you send me a photo of an example where it's not working right please?

**Comment by Shadester** [comment]
![IMG_9809](https://user-images.githubusercontent.com/869974/85205475-6a9f7c00-b2d0-11ea-9321-0373a84eb04b.jpeg)
This one is an example of both Album and Artist.
https://open.spotify.com/track/1687F8k0cz1YBVatKM6GoV?si=ZfO7IVUTSMOIhKZ-y8_xFQ
...And You Will Know Us by the Trail of Dead

**Comment by hankhank10** [comment]
Ok thanks. I’ll have a look into it. Line breaks are actually kind of a pain so I just did it for the title but if it’s proving an issue then I can try to incorporate for the other two lines as well.

By the way I just pushed an update which significantly improves the appearance as it offers a white on black mode which looks pretty cool:

![image](https://user-images.githubusercontent.com/25515609/85206248-b5dd7d00-b318-11ea-8c79-e6e6e9a6cbf8.jpeg)

You can update using git pull - please do let me know if you run into any issues.

**Comment by Shadester** [comment]
Thanks! Yeah, it would be sweet to have it wrap for the other ones too. I guess if extracting the wrapping into a function, it might be easier.

I have also been toying with the idea of using https://github.com/torfsen/python-systemd-tutorial to avoid having to use pm2 (since installing npm and pm2 installs tons of packages).

I might write a pull request with the info.

**Comment by hankhank10** [comment]
Thanks. Yeah you should be able to start go_sonos with systemd or supervisor if you prefer and no changes to the code should be necessary.

I just really like pm2 because you can do everything from the command line rather than messing around with config files, I find the status output easier to see what’s going on with and I really like the web dashboard they have for remote monitoring. But I recognise it’s not that lightweight.

I think you will need npm anyway however if you’re got the Sonos api running on the same machine.
